### ISSUE TITLE
Can't create an instance that doesn't have an internet access

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-ami#30]
*Setup*
AMI: ScyllaDB 2.0.1 (ami-3165e54b)
Cluster size: a single node

*Description*
1) Create a `t2.micro` instance in the same VPC you are going to create a scylla's instance in the (2) below.
2) Create a single instance that has 2 NICs (in this case Amazon doesn't allow auto-assigning public IPs).
3) Wait till our scriptology completes.
4) Login to scylla's instance from the gateway instance created in (1).
5) See how scylla's initialization doesn't complete with the following errors:

```
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: [INFO] Reflector loop...
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: Traceback (most recent call last):
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: File "/usr/lib/scylla/scylla-ami/ds2_configure.py", line 349, in get_seed_list
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: response = urllib2.urlopen(req).read()
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: return opener.open(url, data, timeout)
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: File "/usr/lib64/python2.7/urllib2.py", line 431, in open
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: response = self._open(req, data)
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: '_open', req)
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: result = func(*args)
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: return self.do_open(httplib.HTTPConnection, req)
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: raise URLError(err)
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: URLError: <urlopen error [Errno 110] Connection timed out>
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: [INFO] scylla.yaml configured.
Dec 18 18:03:39 ip-172-16-12-150 scylla_ami_setup[5071]: Creating RAID0 for scylla using 2 disk(s): /dev/xvdb /dev/xvdc
Dec 18 18:03:41 ip-172-16-12-150 scylla_ami_setup[5071]: Loaded plugins: fastestmirror, langpacks
Dec 18 18:03:41 ip-172-16-12-150 scylla_ami_setup[5071]: Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Dec 18 18:04:01 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.us-west-1.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.us-west-1.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10001 milliseconds')
Dec 18 18:04:01 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:04:11 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.us-west-2.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.us-west-2.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10001 milliseconds')
Dec 18 18:04:11 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:04:21 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.us-east-1.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.us-east-1.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10001 milliseconds')
Dec 18 18:04:21 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:04:31 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.eu-west-1.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.eu-west-1.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10001 milliseconds')
Dec 18 18:04:31 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:04:41 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.eu-central-1.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.eu-central-1.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10001 milliseconds')
Dec 18 18:04:41 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:04:51 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.ap-southeast-1.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.ap-southeast-1.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10001 milliseconds')
Dec 18 18:04:51 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:05:01 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.ap-northeast-1.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.ap-northeast-1.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10000 milliseconds')
Dec 18 18:05:01 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:05:11 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.ap-northeast-2.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.ap-northeast-2.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10001 milliseconds')
Dec 18 18:05:11 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:05:21 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.sa-east-1.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.sa-east-1.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10001 milliseconds')
Dec 18 18:05:21 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:05:31 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.ap-southeast-2.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.ap-southeast-2.amazonaws.com/2017.03/main/201703c0ffee/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10001 milliseconds')
Dec 18 18:05:31 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:05:51 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.us-west-1.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.us-west-1.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10001 milliseconds')
Dec 18 18:05:51 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:06:01 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.us-west-2.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.us-west-2.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10001 milliseconds')
Dec 18 18:06:01 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:06:11 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.us-east-1.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.us-east-1.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10001 milliseconds')
Dec 18 18:06:11 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:06:21 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.eu-west-1.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.eu-west-1.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10001 milliseconds')
Dec 18 18:06:21 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:06:31 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.eu-central-1.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.eu-central-1.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10001 milliseconds')
Dec 18 18:06:31 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:06:41 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.ap-southeast-1.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.ap-southeast-1.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10000 milliseconds')
Dec 18 18:06:41 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:06:51 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.ap-northeast-1.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.ap-northeast-1.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10000 milliseconds')
Dec 18 18:06:51 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:07:01 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.ap-northeast-2.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.ap-northeast-2.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10001 milliseconds')
Dec 18 18:07:01 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:07:11 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.sa-east-1.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.sa-east-1.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10001 milliseconds')
Dec 18 18:07:11 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:07:21 ip-172-16-12-150 scylla_ami_setup[5071]: http://packages.ap-southeast-2.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://packages.ap-southeast-2.amazonaws.com/2017.03/updates/ba2b87ec77c7/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 10001 milliseconds')
Dec 18 18:07:21 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:07:22 ip-172-16-12-150 sshd[13791]: Accepted publickey for centos from 172.16.12.164 port 60370 ssh2: RSA 4c:ba:a2:c6:a9:21:83:7a:19:06:4b:a2:65:aa:4f:e8
Dec 18 18:07:22 ip-172-16-12-150 systemd[1]: Created slice user-1000.slice.
Dec 18 18:07:22 ip-172-16-12-150 systemd[1]: Starting user-1000.slice.
Dec 18 18:07:22 ip-172-16-12-150 systemd-logind[4796]: New session 3 of user centos.
Dec 18 18:07:22 ip-172-16-12-150 systemd[1]: Started Session 3 of user centos.
Dec 18 18:07:22 ip-172-16-12-150 systemd[1]: Starting Session 3 of user centos.
Dec 18 18:07:22 ip-172-16-12-150 sshd[13791]: pam_unix(sshd:session): session opened for user centos by (uid=0)
Dec 18 18:07:28 ip-172-16-12-150 sshd[13794]: Received disconnect from 172.16.12.164: 11: disconnected by user
Dec 18 18:07:28 ip-172-16-12-150 sshd[13791]: pam_unix(sshd:session): session closed for user centos
Dec 18 18:07:28 ip-172-16-12-150 systemd-logind[4796]: Removed session 3.
Dec 18 18:07:28 ip-172-16-12-150 systemd[1]: Removed slice user-1000.slice.
Dec 18 18:07:28 ip-172-16-12-150 systemd[1]: Stopping user-1000.slice.
Dec 18 18:07:41 ip-172-16-12-150 sshd[13843]: Accepted publickey for centos from 172.16.12.164 port 60372 ssh2: RSA 4c:ba:a2:c6:a9:21:83:7a:19:06:4b:a2:65:aa:4f:e8
Dec 18 18:07:41 ip-172-16-12-150 systemd[1]: Created slice user-1000.slice.
Dec 18 18:07:41 ip-172-16-12-150 systemd[1]: Starting user-1000.slice.
Dec 18 18:07:41 ip-172-16-12-150 systemd-logind[4796]: New session 4 of user centos.
Dec 18 18:07:41 ip-172-16-12-150 systemd[1]: Started Session 4 of user centos.
Dec 18 18:07:41 ip-172-16-12-150 systemd[1]: Starting Session 4 of user centos.
Dec 18 18:07:41 ip-172-16-12-150 sshd[13843]: pam_unix(sshd:session): session opened for user centos by (uid=0)
Dec 18 18:08:19 ip-172-16-12-150 scylla_ami_setup[5071]: http://mirror.hmc.edu/centos/7.4.1708/os/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirror.hmc.edu/centos/7.4.1708/os/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
Dec 18 18:08:19 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:08:34 ip-172-16-12-150 scylla_ami_setup[5071]: http://mirrors.rcs.alaska.edu/centos/7.4.1708/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:f318:1f00:820::202: Network is unreachable"
Dec 18 18:08:34 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:08:49 ip-172-16-12-150 scylla_ami_setup[5071]: http://repos.forethought.net/centos/7.4.1708/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2604:280:2:3:f816:3eff:fe5b:283b: Network is unreachable"
Dec 18 18:08:49 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:09:19 ip-172-16-12-150 scylla_ami_setup[5071]: http://linux.cc.lehigh.edu/centos/7.4.1708/os/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://linux.cc.lehigh.edu/centos/7.4.1708/os/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
Dec 18 18:09:19 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:09:34 ip-172-16-12-150 scylla_ami_setup[5071]: http://mirrors.maine.edu/CentOS/7.4.1708/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2610:48:100:820::ad: Network is unreachable"
Dec 18 18:09:34 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:10:01 ip-172-16-12-150 systemd[1]: Started Session 5 of user root.
Dec 18 18:10:01 ip-172-16-12-150 systemd[1]: Starting Session 5 of user root.
Dec 18 18:10:01 ip-172-16-12-150 CROND[13901]: (root) CMD (/usr/lib64/sa/sa1 1 1)
Dec 18 18:10:04 ip-172-16-12-150 scylla_ami_setup[5071]: http://denver.gaminghost.co/7.4.1708/os/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://denver.gaminghost.co/7.4.1708/os/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
Dec 18 18:10:04 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:10:19 ip-172-16-12-150 scylla_ami_setup[5071]: http://mirror.scalabledns.com/centos/7.4.1708/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2605:f700:40::1759:6e: Network is unreachable"
Dec 18 18:10:19 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:10:49 ip-172-16-12-150 scylla_ami_setup[5071]: http://mirror.raystedman.net/centos/7.4.1708/os/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirror.raystedman.net/centos/7.4.1708/os/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
Dec 18 18:10:49 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:11:19 ip-172-16-12-150 scylla_ami_setup[5071]: http://mirror.cisp.com/CentOS/7.4.1708/os/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirror.cisp.com/CentOS/7.4.1708/os/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
Dec 18 18:11:19 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:11:49 ip-172-16-12-150 scylla_ami_setup[5071]: http://mirrors.thaidns.co.th/centos/7.4.1708/os/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirrors.thaidns.co.th/centos/7.4.1708/os/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
Dec 18 18:11:49 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:12:35 ip-172-16-12-150 scylla_ami_setup[5071]: http://mirror.rnet.missouri.edu/epel/7/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2610:e0:a010:302:862b:2bff:fe73:9d68: Network is unreachable"
Dec 18 18:12:35 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:12:50 ip-172-16-12-150 scylla_ami_setup[5071]: https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2610:28:3090:3001:dead:beef:cafe:fed6: Network is unreachable"
Dec 18 18:12:50 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:13:20 ip-172-16-12-150 scylla_ami_setup[5071]: http://mirror.oss.ou.edu/epel/7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirror.oss.ou.edu/epel/7/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
Dec 18 18:13:20 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:13:31 ip-172-16-12-150 systemd[1]: Starting Cleanup of Temporary Directories...
Dec 18 18:13:31 ip-172-16-12-150 systemd[1]: Started Cleanup of Temporary Directories.
Dec 18 18:13:40 ip-172-16-12-150 sshd[13845]: Received disconnect from 172.16.12.164: 11: disconnected by user
Dec 18 18:13:40 ip-172-16-12-150 sshd[13843]: pam_unix(sshd:session): session closed for user centos
Dec 18 18:13:40 ip-172-16-12-150 systemd-logind[4796]: Removed session 4.
Dec 18 18:13:40 ip-172-16-12-150 systemd[1]: Removed slice user-1000.slice.
Dec 18 18:13:40 ip-172-16-12-150 systemd[1]: Stopping user-1000.slice.
Dec 18 18:13:41 ip-172-16-12-150 sshd[13923]: Accepted publickey for centos from 172.16.12.164 port 60374 ssh2: RSA 4c:ba:a2:c6:a9:21:83:7a:19:06:4b:a2:65:aa:4f:e8
Dec 18 18:13:41 ip-172-16-12-150 systemd[1]: Created slice user-1000.slice.
Dec 18 18:13:41 ip-172-16-12-150 systemd[1]: Starting user-1000.slice.
Dec 18 18:13:41 ip-172-16-12-150 systemd-logind[4796]: New session 6 of user centos.
Dec 18 18:13:41 ip-172-16-12-150 systemd[1]: Started Session 6 of user centos.
Dec 18 18:13:41 ip-172-16-12-150 systemd[1]: Starting Session 6 of user centos.
Dec 18 18:13:41 ip-172-16-12-150 sshd[13923]: pam_unix(sshd:session): session opened for user centos by (uid=0)
Dec 18 18:13:50 ip-172-16-12-150 scylla_ami_setup[5071]: https://pubmirror2.math.uh.edu/fedora-buffet/epel/7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://pubmirror2.math.uh.edu/fedora-buffet/epel/7/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
Dec 18 18:13:50 ip-172-16-12-150 scylla_ami_setup[5071]: Trying other mirror.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: scylla-ami-setup.service start operation timed out. Terminating.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: Failed to start Scylla AMI Setup.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: Dependency failed for Scylla Server.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: Dependency failed for Scylla JMX.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: Job scylla-jmx.service/start failed with result 'dependency'.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: Dependency failed for Run Scylla Housekeeping daily mode.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: Job scylla-housekeeping-daily.timer/start failed with result 'dependency'.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: Dependency failed for Run Scylla Housekeeping restart mode.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: Job scylla-housekeeping-restart.timer/start failed with result 'dependency'.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: Job scylla-server.service/start failed with result 'dependency'.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: Unit scylla-ami-setup.service entered failed state.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: scylla-ami-setup.service failed.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: Reached target Multi-User System.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: Starting Multi-User System.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: Reached target Graphical Interface.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: Starting Graphical Interface.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: Started Stop Read-Ahead Data Collection 10s After Completed Startup.
Dec 18 18:13:59 ip-172-16-12-150 systemd[1]: Starting Update UTMP about System Runlevel Changes...

```

**Comment by tzach** [comment]
Thanks, @vladzcloudius this is a common use case.
@syuu1228 where is the problem here? it makes sense an AMI without external connection will fail to connect to the reflector, is it the issue?
If so, we should allow to disable it with a user parameter (maybe we already can?)

**Comment by CarlGill** [comment]
For those interested, I found the code for reflector.php here:
https://github.com/riptano/ComboAMI/blob/2.6/reflector.php

Should allow you to host the current AMI's offline.
